import { defineTool } from '@opentabs-dev/plugin-sdk';
import { z } from 'zod';
import { listConversations as fetchConversations } from '../copilot-api.js';
import { conversationSchema, mapConversation } from './schemas.js';

export const listConversations = defineTool({
  name: 'list_conversations',
  displayName: 'List Conversations',
  description:
    'List the account\'s Copilot conversations, newest first — the same list the sidebar\'s history shows. Titles are generated by Copilot after the first reply, so a very recent chat can come back with an empty title (the sidebar renders those as "New conversation"). Use a returned id with get_conversation or send_message.',
  summary: 'List recent Copilot conversations',
  icon: 'list',
  group: 'Conversations',
  input: z.object({
    limit: z
      .number()
      .int()
      .min(1)
      .max(200)
      .optional()
      .describe('Maximum number of conversations to return (default 30, max 200).'),
  }),
  output: z.object({
    conversations: z.array(conversationSchema).describe('Conversations, newest first'),
  }),
  handle: async params => {
    const conversations = await fetchConversations(params.limit ?? 30);
    return { conversations: conversations.map(mapConversation) };
  },
});
